DELETE http://localhost:3001/api/blogs/620575b2480b2ad1ff70e155
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlYW5nb2F0cyIsImlkIjoiNjIwNTY5MzI1MGUyNmYwZjQzMzVjNjA5IiwiaWF0IjoxNjQ0NTI1Njk0fQ.STTIXNER2q9tUmAxWGDa3PaGLpVPW6ZkyewGbABqyBA
//Replace id with testing id
